name: Tests

on:
  push:
    branches:
      - "master"

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: cachix/install-nix-action@v13
      - uses: cachix/cachix-action@v10
        with:
          name: dapp

      - name: Install dependencies
        run: nix-shell --run 'make'

      - name: Check gas snapshots
        run: make gas

      - name: Run tests
        run: make test
        env:
          DEEP_FUZZ: false